{{- if and (not .Values.db.external.enabled) (.Values.db.persistence.enabled) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-db-pvc
  labels:
    app: {{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- if .Values.db.persistence.storageClass }}
  storageClassName: "{{ .Values.db.persistence.storageClass }}"
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-audit-db-pvc
  labels:
    app: {{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.size | quote }}
{{- if .Values.db.persistence.storageClass }}
  storageClassName: "{{ .Values.db.persistence.storageClass }}"
{{- end }}
{{- end }}
