{{- if .Values.envoy.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-gateway-headless
  labels:
    app: {{ .Release.Namespace }}-gateway
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  clusterIP: None
  type: ClusterIP
  selector:
    app: {{ .Release.Namespace }}-gateway
  ports:
  {{- range $port := .Values.gate.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}

{{- end }}