apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ke.certsSecret.name }}
  namespace: {{ .Values.ke.namespace }}
data:
  aqua_ke.crt: {{ template "serverCertificate" . }}  # place server cert
  aqua_ke.key: {{ template "serverKey" . }}  # place server key